#!/bin/bash

BLACKLIST=(
	Simulator
)

IFS=,
options=(
	style=round
	width=4.0
	hidpi=off
	active_color=0xffffdf20
	inactive_color=0xffbcbcbc
	order=above
	blacklist="${BLACKLIST[*]}"
)
unset IFS

borders "${options[@]}"